name: NodeJS with Webpack

on:
  push:
    tags: 
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: Zip
      uses: byteever/action-build-zip@master
      with:
        filename: 'research-amp.zip'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "research-amp.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
